//
//  ZOSApi.swift
//  Zowe SDK
//
//  This program and the accompanying materials are made available under the terms of the
//  Eclipse Public License v2.0 which accompanies this distribution, and is available at
//  https://www.eclipse.org/legal/epl-v20.html
//  SPDX-License-Identifier: EPL-2.0
//
//  Copyright © 2020 Contributors to the Zowe Project. All rights reserved.
//

import Foundation

/// z/OS REST API base class
public class ZOSApi {
    
    // MARK: - ZOSApi private members
    
    /// z/OS URI path endpoint
    private let defaultServiceUrl: String

    /// z/OS HTTP request default headers
    private var defaultHeaders: Dictionary<String, String> {
        [
            "Authorization": "Basic " + encodedCredentials,
            "Content-Type": "application/json; charset=UTF-8",
            "X-CSRF-ZOSMF-HEADER": "true"
        ]
    }
    
    /// Base64 encoded credentials in <mainframeId>:<password> format
    /// - See Also: [Using the z/OSMF REST services :: Basic authentication](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_RESTServices.htm#IZUHPINFO_RESTServices__basicauth)
    private var encodedCredentials: String {
        let credentials = connection.user + ":" + connection.password
        let credentialsData = credentials.data(using: .utf8)
        let credentialsOptions = Data.Base64EncodingOptions(rawValue: 0)
        guard let credentialsEncoded = credentialsData?.base64EncodedString(options: credentialsOptions) else {
            fatalError(ZOSError.base64EncodedString.errorDescription!)
        }
        
        return credentialsEncoded
    }
    
    // MARK: - ZOSApi internal fields
    
    /// z/OS REST API connection object (generated by the ZoweSDK object)
    internal let connection: ZOSConnection
    
    /// z/OS REST API full URL endpoint
    internal var requestEndpoint: URL {
        var urlComponents = URLComponents()
        urlComponents.scheme = "https"
        urlComponents.percentEncodedHost = connection.host
        urlComponents.port = Int(connection.port ?? "")
        urlComponents.path = defaultServiceUrl
        guard let verifiedUrl = urlComponents.url else {
            fatalError(ZOSError.invalidUrlAddress.errorDescription!)
        }
        return verifiedUrl
    }
    
    /// HTTP request default arguments
    internal var requestArguments: (url: URL, headers: Dictionary<String, String>, body: Any?) {
        (
            requestEndpoint,
            defaultHeaders,
            nil
        )
    }
    
    /// Zowe SDK default session arguments
    internal var sessionArguments: (Double, Double) {
        (
            timeout: 30.0,
            timeoutForRequest: 60.0
        )
    }
    
    /// z/OS REST API HTTP request object
    internal var requestHandler: ZOSRequestHandler {
        ZOSRequestHandler(connection, sessionArguments)
    }
    
    // MARK: - ZOSApi constructor
    
    /// ZosmfApi object constructor
    /// - Parameters:
    ///   - connection: z/OS REST API connection object (generated by the ZoweSDK object)
    ///   - defaultUrl: The base default endpoint url used by the REST API
    internal init(
        _ connection: ZOSConnection,
        _ defaultUrl: String
    ) {
        self.connection = connection
        self.defaultServiceUrl = defaultUrl
    }
    
    // MARK: - ZOSApi internal methods
    
    /// Prepares URL object and verifies its validity
    /// - Parameters:
    ///   - path: URL path component to append.
    ///   - queryItems: Optional parameter for URL query items to append if any.
    /// - Returns: Verified URL object to use for HTTP request.
    internal func prepareUrl(
        path: String = "",
        queryItems: [URLQueryItem]? = nil
    ) -> URL {
        var urlComponents = URLComponents()
        urlComponents.path = path
        urlComponents.queryItems = queryItems
        guard let verifiedUrl = urlComponents.url(relativeTo: requestArguments.url) else {
            fatalError(ZOSError.invalidUrlAddress.errorDescription!)
        }
        return verifiedUrl
    }
}
